/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmengine_free: (a: number, b: number) => void;
export const __wbg_wasmstorycatalog_free: (a: number, b: number) => void;
export const wasmengine_availableEvents: (a: number) => [number, number];
export const wasmengine_canAccessEvent: (a: number, b: number, c: number) => number;
export const wasmengine_currentChoicesBytes: (a: number) => any;
export const wasmengine_currentEventId: (a: number) => [number, number];
export const wasmengine_currentEventTextBytes: (a: number) => any;
export const wasmengine_getCurrentEvent: (a: number) => [number, number, number];
export const wasmengine_getHistory: (a: number) => [number, number, number];
export const wasmengine_getStat: (a: number, b: number, c: number) => bigint;
export const wasmengine_getStateJson: (a: number) => [number, number];
export const wasmengine_listFlags: (a: number) => [number, number];
export const wasmengine_listStats: (a: number) => [number, number, number];
export const wasmengine_listStoryTags: (a: number) => [number, number];
export const wasmengine_listTags: (a: number) => [number, number];
export const wasmengine_makeChoice: (a: number, b: number) => [number, number, number];
export const wasmengine_new: (a: number, b: number) => [number, number, number];
export const wasmengine_setStateJson: (a: number, b: number, c: number) => [number, number];
export const wasmstorycatalog_createEngine: (a: number, b: number) => number;
export const wasmstorycatalog_createEngineByName: (a: number, b: number, c: number) => number;
export const wasmstorycatalog_isEmpty: (a: number) => number;
export const wasmstorycatalog_len: (a: number) => number;
export const wasmstorycatalog_listStories: (a: number) => [number, number, number];
export const wasmstorycatalog_new: () => number;
export const wasmstorycatalog_register: (a: number, b: number, c: number) => [number, number];
export const wasmstorycatalog_storiesWithAllTags: (a: number, b: number, c: number) => [number, number, number];
export const wasmstorycatalog_storiesWithAnyTags: (a: number, b: number, c: number) => [number, number, number];
export const wasmstorycatalog_storiesWithTag: (a: number, b: number, c: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
