[package]
name = "cyoa-native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
cyoa-runtime = { path = "../cyoa-runtime" }
cyoa-bytecode = { path = "../cyoa-bytecode" }
serde_json = "1.0"

[dev-dependencies]
cyoa-compiler = { path = "../cyoa-compiler" }
