/**
 * CYOA WASM Engine — TypeScript declarations.
 *
 * Auto-generated by `wasm-pack` but hand-curated for clarity.
 * The WASM module exports two classes: `WasmStoryCatalog` and `WasmEngine`.
 *
 * Each story is an independent `WasmEngine` instance. Use the `StoryCatalog`
 * to register multiple stories, filter by tags, and create engines.
 */

/**
 * A registry of compiled stories with tag-based filtering.
 *
 * Use this to discover stories by tag, then create an `WasmEngine` to play.
 */
export class WasmStoryCatalog {
  constructor();

  /**
   * Register a compiled story from bytecode bytes.
   * @param bytes - The `.cyoa.bc` bytecode file as a Uint8Array.
   * @throws If the bytecode fails to decode.
   */
  register(bytes: Uint8Array): void;

  /** Number of registered stories. */
  len(): number;

  /** Whether the catalog is empty. */
  isEmpty(): boolean;

  /**
   * List all registered stories.
   * @returns Array of `{ name: string, tags: string[] }` objects.
   */
  listStories(): Array<{ name: string; tags: string[] }>;

  /**
   * Find all stories that have a specific tag.
   * @returns Array of `{ name: string, tags: string[] }` objects.
   */
  storiesWithTag(tag: string): Array<{ name: string; tags: string[] }>;

  /**
   * Find all stories that have ALL of the specified tags.
   *
   * @param tagsJson - A JSON array of tag strings, e.g. `'["fantasy", "exploration"]'`.
   * @returns Array of `{ name: string, tags: string[] }` objects.
   */
  storiesWithAllTags(tagsJson: string): Array<{ name: string; tags: string[] }>;

  /**
   * Find all stories that have ANY of the specified tags.
   *
   * @param tagsJson - A JSON array of tag strings, e.g. `'["fantasy", "combat"]'`.
   * @returns Array of `{ name: string, tags: string[] }` objects.
   */
  storiesWithAnyTags(tagsJson: string): Array<{ name: string; tags: string[] }>;

  /**
   * Create an `WasmEngine` for the story at the given index.
   * @returns `WasmEngine` or `undefined` if out of bounds.
   */
  createEngine(index: number): WasmEngine | undefined;

  /**
   * Find a story by name and create an `WasmEngine` for it.
   * @returns `WasmEngine` or `undefined` if not found.
   */
  createEngineByName(name: string): WasmEngine | undefined;

}

/**
 * A CYOA story engine instance.
 *
 * Each engine is independent — state is never shared between instances.
 * Create one per story (main quest, side quests, etc.).
 */
export class WasmEngine {
  /**
   * Create an engine directly from compiled bytecode bytes.
   *
   * @param bytes - The `.cyoa.bc` bytecode file as a Uint8Array.
   * @throws If the bytecode fails to decode.
   */
  constructor(bytes: Uint8Array);

  /**
   * Get the current event's internal ID.
   */
  currentEventId(): string;

  /**
   * Get the current event as a JS object:
   * ```json
   * { "id": "old_ruins", "text": ["...", "..."], "choices": ["...", "..."] }
   * ```
   *
   * Templates are already rendered (e.g. `{{gold}}` → `42`).
   * Choices with unmet prerequisites are excluded.
   */
  getCurrentEvent(): {
    id: string;
    text: string[];
    choices: string[];
  };

  /**
   * ZERO-COPY: Returns a `Uint8Array` view into WASM linear memory
   * containing all current event text paragraphs, newline-separated.
   *
   * The bytes are valid until the next method call on this engine.
   * Use `TextDecoder` to decode:
   * ```js
   * const bytes = engine.currentEventTextBytes();
   * const text = new TextDecoder().decode(bytes);
   * ```
   */
  currentEventTextBytes(): Uint8Array;

  /**
   * ZERO-COPY: Returns a `Uint8Array` view into WASM linear memory
   * containing all current choice texts, newline-separated.
   *
   * The bytes are valid until the next method call on this engine.
   */
  currentChoicesBytes(): Uint8Array;

  /**
   * Make a choice at the given 0-based index.
   * Only visible choices (prerequisites met) are indexed.
   *
   * @returns `{ effectText: string[], gameStateChanged: boolean }`
   */
  makeChoice(choiceIndex: number): {
    effectText: string[];
    gameStateChanged: boolean;
  };

  /**
   * Get the choice history as an array of:
   * ```json
   * [{ "eventId": "...", "choiceIndex": 0, "choiceText": "..." }]
   * ```
   */
  getHistory(): Array<{
    eventId: string;
    choiceIndex: number;
    choiceText: string;
  }>;

  /**
   * Get the full player state as a JSON string (for save files).
   * The JSON includes `stats`, `flags`, `tags`, `current_event`, and
   * `choice_history` — enabling full save/load between sessions.
   *
   * The returned string is valid until the next method call on this engine.
   */
  getStateJson(): string;

  /**
   * Restore state from a JSON string produced by `getStateJson()`.
   */
  setStateJson(json: string): void;

  /**
   * Get stats as a JS object mapping stat names to current values.
   * ```js
   * { "hp": 40, "gold": 3, "courage": 5 }
   * ```
   */
  listStats(): { [key: string]: number };

  /** Get a stat value by name. Returns 0 if unset. */
  getStat(name: string): bigint;

  /**
   * List story-level tags (static metadata declared in the .cyoa file).
   * These are distinct from runtime tags applied during play.
   */
  listStoryTags(): string[];

  /** List runtime tags currently applied during play. */
  listTags(): string[];

  /** List all runtime flags currently set. */
  listFlags(): string[];

  /** Check if an event by ID exists in the story. */
  canAccessEvent(id: string): boolean;

  /**
   * List all event IDs in the story (useful for quest logs).
   */
  availableEvents(): string[];
}

/** Initializes the WASM module. Returns a Promise that resolves when ready. */
export default function init(): Promise<void>;
